### ISSUE TITLE
Does not implement PhpTypeProvider2

### ISSUE THREAD

**Issue by devtop** [pulyaevskiy/phpstorm-phpdi#1]
I could not manage to compile the plugin by my self. I spent some hour to fix, but I got stuck into the following interface implementation problem.

```
java.lang.Throwable: Extension class com.pulyaevskiy.phpstorm.phpdi.PhpDiTypeProvider does not implement interface com.jetbrains.php.lang.psi.resolve.types.PhpTypeProvider2
```

To me it seems, that the implementation is absolutely sufficient. I don't know, why the compiler is unhappy with it. I usually develop in php and I'm used to write IntelliJ plugins. Sorry for any dumb questions.

Maybe it's my development environment? I'm using the SDK from java-7-openjdk and the php-openapi from phpstorm 8.0.3 on Linux Mint 17.1. 

Would be great if you can give me a hand.

**Comment by pulyaevskiy** [comment]
Thanks for feedback!

Not sure what your use case is, but if you just need to install this plugin in PhpStorm you can install it via official repository now: https://plugins.jetbrains.com/plugin/7694

If you actually want to tweak this plugin I can take a look a bit later. This error does seem strange and looks like configuration issue.

**Comment by devtop** [comment]
Thanks for your help. The plugin binary from jetbrains works fine. That means I do something wrong, while compilation. I actually try to play a little with the code to see if I can contribute in any way or at least learn a bit of doing plugin development. I would appreciate it if you could look into it later.

The error pops up during runtime (after start) of Phpstorm. I guess it's a configuration problem, too. I have no clue of what's missing in my setting. I'll stay tune. When I got it fixed, I'll leave a note.

I hope I don't bother you. Just hoping for any kind of pointer.

**Comment by pulyaevskiy** [comment]
Hey,
Sorry for the delay. I checked again with latest version of IDEA and PHPStorm, everything looks good.

Did you get this resolved by any chance?

Also did you use official guide to setup IDEA for plugin development? This one:
https://confluence.jetbrains.com/display/IDEADEV/Getting+Started+with+Plugin+Development

Also, you mentioned you're using java-7-openjdk, but the guide says Java 1.6 is recommended.

**Comment by pulyaevskiy** [comment]
@devtop I'll close this issue for now. Feel free to reopen if/when you get any new info.

**Comment by regisbelson** [comment]
I had the same error while trying to compile another plugin. To fix this, do NOT add php-openapi.jar and php.jar as libraries to the plugin project, but add them to the IntelliJ SDK libraries.
