### ISSUE TITLE
Plugin seems to not working ... ?

### ISSUE THREAD

**Issue by e-belair** [pulyaevskiy/phpstorm-phpdi#8]
Hi, I'm using the plugin for a long time without any problem.
But since few days, It seems to not working anymore...
See the capture below:
![Sélection_045](https://user-images.githubusercontent.com/596562/54914923-62eaff00-4ef6-11e9-96cb-b40f8a4fa52d.png)

PhpStorm 2018.3.5
Build #PS-183.5912.26, built on March 7, 2019
JRE: 1.8.0_152-release-1343-b28 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-46-generic

Also, I've read a comment on the plugin page that phpStorm support natively. So I disabled the plugin then try to see but nothing changed ...
https://plugins.jetbrains.com/plugin/7694-php-di-plugin#comment=23531

**Comment by mnapoli** [comment]
@e-belair yes PhpStorm supports PSR-11 by default.

Could you check that `getServiceLocator()`'s return type is correctly handled by PhpStorm and detected either as a PSR-11 `ContainerInterface` or a `DI\Container`? Do clicking on `get()` works?

**Comment by e-belair** [comment]
Thanks for reply. Finally I could figure out by restarting phpStorm ..... Don't understand what happened, but after restart, the plugin worked again... Weird!
Sorry for wasting your time

**Comment by e-belair** [comment]
Hi, I'm sorry but the problem still appears.... Very strange though
So clicking `get()` work
The `getServiceLocator` return type is a `ServiceLocatorInterface` that contain `get()` and `set()` methods.
It's not implementing `ContainerInterface` or `DI\Container` (the project is pretty old)
But it's been working for years so I wonder what is happening now.

**Comment by lovelock** [comment]
Cannot find the comment, I've used the plugin for years and works very well, after upgrade PhpStorm to 2019.3, the plugin stopped working, I forked the source but cannot figure out how to build it, there's no document at all.
A possible reason it the deprecation of typeProvider2, maybe rebuild with typeProvider3 would fix the problem.

**Comment by pulyaevskiy** [comment]
I was under impression that php storm should already support this use case without this plugin. Wondering if anyone checked for a setting somewhere in the ide to switch on?

Sorry I myself haven’t used php storm for a few years now, this is why I’m pretty slow here.

**Comment by pulyaevskiy** [comment]
Also check out this guide, maybe it’ll help?


http://php-di.org/doc/ide-integration.html

**Comment by lovelock** [comment]
God you saved my life!!! I've checked out a similar article in jetbrains website but cannot figure out how to adapt it for my project. This article described the solution very well. Thank you.

I think we should update this great project's readme and let more people know how to solve the problem without the plugin.

**Comment by e-belair** [comment]
I agree PhpStorm can handle DI integration now. But there were issues about their functionality too ^^"
